### ISSUE TITLE
关于一直停留在在访问google()

### ISSUE THREAD

**Issue by jinhuizxc** [wheat7/NationalGeographic#1]
楼主，我把你的代码下载下来运行，一直在gradle:一直在加载中，请问怎么解决？

**Comment by wheat7** [comment]
由于一些众所周知的原因，有很多依赖库是在墙外无法下载的，需要科学上网，这个问题作为安卓开发者也会非常常见，建议掌握自己的科学上网方法

**Comment by jinhuizxc** [comment]
好吧，我再找找相关资料好了。谢谢
